### ISSUE TITLE
Viewing JATOS locally after using docker-compose on server

### ISSUE THREAD

**Issue by mpariente** [JATOS/JATOS_with_docker_compose#1]
Hello, 

Thank you very much for your work with JATOS, it looks great ! 😍 

I'm starting to setup JATOS on OVHCloud to run experiments, and used the docker-compose version, which looked the simplest. 
I would like to run JATOS remotely and access it on my browser, but cannot make it work for now. 

The docker-compose works fine: 
![image](https://github.com/JATOS/JATOS_with_docker_compose/assets/18496796/1ab04f69-5324-44b3-89a4-7ba74b51b708)

But I obviously cannot connect to `127.0.0.1:9000` on my browser, because JATOS runs on the server. 
### Things I've tried 
- I've read the pages on installing JATOS on a server (all the pages : DigitalOcean, AWS, own server)
- I have allowed public access 
- I do have IPv4 and IPv6 info from the node (and Gateways)
- I've attached an SSH key to the node, and tried to forward the port 9000 with  `ssh -L 9000:127.0.0.1:9000 ubuntu@xx.xxx.xx.xx` (no luck)
- I've tried setting the JATOS port in `compose.yml` to `80:9000` as in the DigitalOcean srtup but it failed

Could you please help me ? 🙃 

**Disclaimers :**
- I'm more of a Python dev than anything, sorry if the questions are basic.
- I've never used reverse proxys like Nginx.
- I'm not an web/ssh guru.

Cheers !

**Comment by kristian-lange** [comment]
Hi!

Sorry for taking some time to answer. Great you like JATOS :)

> used the docker-compose version, which looked the simplest.

If you know your way around Docker and Docker Compose, I agree.

> But I obviously cannot connect to 127.0.0.1:9000 on my browser, because JATOS runs on the server.

Yes. Did you try to access JATOS with your server's public IP? I see you are using a (reverse) proxy. Do you have a domain name for your server? If yes, you have to config your reverse proxy (Nginx?) to accept traffic for this domain. Have a look at https://www.jatos.org/JATOS-with-Nginx.html and https://www.jatos.org/JATOS-with-Docker-Compose.html. If it's Nginx, you can config your nginx.conf, everywhere you find the comment `# --> Change to your domain <--`. 

> I do have IPv4 and IPv6 info from the node (and Gateways)

Try with your public IP address and port 80

> I've attached an SSH key to the node, and tried to forward the port 9000 with ssh -L 9000:127.0.0.1:9000 ubuntu@xx.xxx.xx.xx (no luck)

Whoa, tame your horses, that's not necessary.

> I've tried setting the JATOS port in compose.yml to 80:9000 as in the DigitalOcean srtup but it failed

Also not necessary. The reverse proxy does this for you.

To setup JATOS with a reverse proxy is usually pretty straight forward (although I didn't use OVHCloud myself), no extraordinary things. But if you've never used a reverse proxy before you first have to get into this world first. 

Cheers!
Kristian

**Comment by mpariente** [comment]
Thank you very much for your answer ! 

The reverse proxy was out of my league indeed, and I didn't manage to make it work yet. 

I could make JATOS work with the simple `docker run -d --restart=always -p 80:9000 jatos/jatos:latest` without Nginx, so I'm pretty happy already 🤩 

Without modifying the `nginx.conf`, pasting the IP address of the node on the browser, I get a page redirecting me to Nginx for more configuration. And changing the `nginx.conf` to change the example with the IP address of the node (I don't have a domain name, or is it the one from OVH ?), I cannot connect to it anymore.

**Comment by kristian-lange** [comment]
> I could make JATOS work with the simple docker run -d --restart=always -p 80:9000 jatos/jatos:latest without Nginx, so I'm pretty happy already 🤩

The easiest solution is often the best :) . You don't need an reverse proxy if you just want to access your server by its IP without a domain or encryption.

> Without modifying the nginx.conf, pasting the IP address of the node on the browser, I get a page redirecting me to Nginx for more configuration. And changing the nginx.conf to change the example with the IP address of the node (I don't have a domain name, or is it the one from OVH ?), I cannot connect to it anymore.

Not sure what's going on here. Maybe you used the wrong IP (sometimes the providers show you several ones and you have to figure out which one is the public one). But I've never worked with OVH.

**Comment by mpariente** [comment]
Thanks again @kristian-lange for your answer ! 

I'll close the issue as this seems to be related to OVH rather than Jatos.
